### PR TITLE
Fix lowerBound <= upperBound, fixes #24

### LINKED ISSUE #24: Thread 1: Fatal error: Range requires lowerBound <= upperBound
### Description

Screenshot 2024-03-03 alle 18 18 00

### To Reproduce

1) Create a single file project
2) Git init
3) Open the project with AE

### Version information

Aurora Editor: 1.0 (1)
Commit: 2afdf0378f8425a1722d66bf4dbcfdfc99f1f10b
MacOS: 14.1.1 (23B81)
Xcode: 15.2 (15C500b)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0xWDG**
Fix lowerBound <= upperBound, fixes #24

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by 0xWDG** [comment]
@aurora-care-bear please approve this pr

**Review by aurora-care-bear — APPROVED** [review]
Approved on behalf of @0xWDG

**Comment by aurora-care-bear** [comment]
Hey @0xWDG,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Review by nanashili — APPROVED** [review]

**Pull request merged**
